version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      agave-solana-stack:
        patterns:
          - "agave-*"
          - "solana-transaction-*"
      other-updates:
        exclude-patterns:
          - "agave-*"
          - "solana-transaction-*"
